# Generated by Django 4.2.4 on 2023-10-05 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('portions', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('cooking_hours', models.PositiveIntegerField(default=0)),
                ('cooking_minutes', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='recipe_images/%(title)s/')),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks')], max_length=20)),
                ('ingredients', models.JSONField(default=dict)),
                ('steps', models.TextField()),
                ('is_approved', models.BooleanField(choices=[(True, 'Approved'), (False, 'On moderation')], default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
