# Generated by Django 4.2.4 on 2023-10-18 11:17

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_author_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=recipes.models.recipe_image_path),
        ),
    ]
