# Generated by Django 4.2.4 on 2023-10-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
