# Generated by Django 4.2.4 on 2023-10-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_delete_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks'), ('Miscellaneous', 'Other')], max_length=20),
        ),
    ]
