# Generated by Django 5.0b1 on 2023-11-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='portions',
            field=models.PositiveIntegerField(blank=True, default=1, max_length=3, null=True),
        ),
    ]
