# Generated by Django 4.2.4 on 2023-10-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='recipe',
            new_name='favorite_recipe',
        ),
    ]
