# Generated by Django 5.0b1 on 2023-11-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
